name: 4pilaresAdvisor Release

on: 
  push:
    paths:
    - "*.ex5"
    - ".github/workflows/*.yml"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get version tag
      id: get_version
      run: echo ::set-output name=VERSION::$(iconv -f utf-16 -t utf-8 4PilaresAdvisor.mq5 | grep version | sed -r 's/.+"(.+)".+/\1/')

    - uses: rlespinasse/github-slug-action@1.1.1
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_HEAD_REF_SLUG }}
        echo ${{ env.GITHUB_BASE_REF_SLUG }}
      
    - name: Upload ex5
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.GITHUB_REF_SLUG }}
        prerelease: false
        title: ${{ steps.get_version.outputs.VERSION }}
        files: |
          *.ex5
